schema_version: 1

package:
  name: csdl_alpha
  version: "0.0.0a2"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy
    - scipy
    - sympy
    - rustworkx
    - networkx
    - h5py
    - pydot
    - pytest

tests:
  - python:
      imports:
        - csdl_alpha

about:
  homepage: https://github.com/LSDOlab/csdl_alpha
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Computational System Design Language.
